-- which customer has maximum order

select Cutomer_name,count(orders.CustomerID) AS ORD
from customers
join orders
on (customers.CustomerID = orders.CustomerID)
group by orders.CustomerID
order by ORD DESC
limit 1;

-- which customer has the lowest order

select Cutomer_name,count(orders.CustomerID) AS ORD
from customers
join orders
on (customers.CustomerID = orders.CustomerID)
group by orders.CustomerID
order by ORD asc
limit 1;

-- highest selling product

select product_name,sum(order_detail.quantity) as product_sell
from product
join order_detail
on (product.product_id = order_detail.product_id)
group by product_name
order by product_sell desc
limit 1;


-- lowest selling product

select product_name,sum(order_detail.quantity) as product_sell
from product
join order_detail
on (product.product_id = order_detail.product_id)
group by product_name
order by product_sell asc
limit 1;

-- average rating of the product

select product_name,avg(rating) as rating
from product
join reviews
on (product.product_id = reviews.product_id)
group by product_name;

-- no of product in each category

select category_name,count(product.Category_id)
from categories
join product
on (categories.Category_id = product.Category_id)
group by category_name;

-- how much order has been been placed on particular dates

select count(Order_id) as total_order
from orders
where Order_date between "2024-02-11" and "2024-03-04";

-- revenue done by each product

select product_name,sum(product.price * order_detail.Quantity) as total_sales
from product
join order_detail
on (product.Product_id = order_detail.product_id)
group by product_name;


-- top 5 product which are giving highest profit

select product_name,sum(product.price * order_detail.Quantity) as total_sales
from product
join order_detail
on (product.Product_id = order_detail.product_id)
group by product_name
order by total_sales desc
limit 5;


-- top 5 product which are giving lowest profit

select product_name,sum(product.price * order_detail.Quantity) as total_sales
from product
join order_detail
on (product.Product_id = order_detail.product_id)
group by product_name
order by total_sales asc
limit 5;

-- which customer has 2nd highest order 

select Cutomer_name, count(orders.Order_id) as no_of_order
from customers
join orders
on (customers.CustomerID = orders.CustomerID)
group by Cutomer_name
order by no_of_order desc
limit 1 offset 1;


-- no of product sold by each category

select category_name,sum(order_detail.quantity) as product_sell
from categories
join product
on (product.Category_id = categories.Category_id)
join order_detail
on (order_detail.product_id = product.Product_id)
group by category_name;

-- which category has highest sales

select category_name,sum(order_detail.quantity) as product_sell
from categories
join product
on (product.Category_id = categories.Category_id)
join order_detail
on (order_detail.product_id = product.Product_id)
group by category_name
order by product_sell desc
limit 1;

-- which category has lowest sales

select category_name,sum(order_detail.quantity) as product_sell
from categories
join product
on (product.Category_id = categories.Category_id)
join order_detail
on (order_detail.product_id = product.Product_id)
group by category_name
order by product_sell asc
limit 1;

-- profit generated by each categories

select category_name,sum(product.price * order_detail.Quantity) as total_sales
from categories
join product
on (product.Category_id = categories.Category_id)
join order_detail
on (order_detail.product_id = product.Product_id)
group by category_name;


-- which categories generates maximum profit 

select category_name,sum(product.price * order_detail.Quantity) as total_sales
from categories
join product
on (product.Category_id = categories.Category_id)
join order_detail
on (order_detail.product_id = product.Product_id)
group by category_name
order by total_sales desc
limit 1;

-- which categories generates lowest profit 

select category_name,sum(product.price * order_detail.Quantity) as total_sales
from categories
join product
on (product.Category_id = categories.Category_id)
join order_detail
on (order_detail.product_id = product.Product_id)
group by category_name
order by total_sales asc
limit 1;

-- which product has the lowest rating

select Product_name,avg(reviews.Rating) as Rating
from product
join reviews
on (product.Product_id = reviews.Product_id)
group by Product_name
order by Rating asc
limit 1;

-- profit generated on particular date

select Order_date ,sum(product.price * order_detail.Quantity) as sales
from orders
join order_detail
on (order_detail.order_id = orders.order_id)
join product
on (product.Product_id = order_detail.product_id)
where Order_date = "2024-03-11";

-- profit generated on between dates

select Order_date ,sum(product.price * order_detail.Quantity) as sales
from orders
join order_detail
on (order_detail.order_id = orders.order_id)
join product
on (product.Product_id = order_detail.product_id)
where Order_date between "2024-02-10" and "2024-03-20"
group by Order_date;